# docker-compose.yml
networks:
  todoapp-net:
services:
  pythonapp:
    env_file:
      - .env
    container_name: todoapp
    image: todoapp:${TAG_VERSION_TODOAPP}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - todoapp-net
    depends_on:
      - mysql
    restart: unless-stopped
  mysql:
    image: mysql-local:${TAG_VERSION_MYSQL}
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: my-sql
    ports:
      - "3306:3306"
    volumes:
      - todoapp-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TAG_VERSION_MYSQL=${TAG_VERSION_MYSQL}
    networks:
      - todoapp-net
volumes:
  todoapp-db-data:
